### ISSUE TITLE
Note routines as automated or manual

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#101]

**Comment by LL782** [comment]
Notes on https://airtable.com/applsFPbVXTrmlkLC/tblKdtFDcvJFyRGYg/viwZ0ONkU0t5IHBwd?blocks=hide

Only "transactional emails" are marked as automated. Everything else seems manual to me

@anibe do you have any ideas on this one?

**Comment by anibe** [comment]
@LL782 IMO I think we should have some level of automation across board, considering size of the team and the effort it takes to do manual posting. And by "automated" I could also be referring to "hybrid" where you post somewhere (for eg WordPress blog) and a plugin auto-pushes it to other platforms.

We discussed [Buffer ](https://buffer.com/)before, and I think having a tool do the job of content manager would be a good investment.

**Comment by LL782** [comment]
@anibe I see what you mean. I agree multiplying a manual post to multiple platforms could be useful.

Let's make a distinction between truly automated, e.g. the transactional emails and these "hybrid" routines. 
Maybe this should be a separate ticket. I had a different intention when I wrote this one

-  https://github.com/LL782/LL782/issues/105
