### ISSUE TITLE
Identify which comms routines should be auto-assisted

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#105]
## Why

1. To increase the reach of our social media posts
3. To make more time for other business activities

## What

- [x] Define which manual comms routines could be automatically multiplied
- [x] Create further issues (see comments)
    - #113
    - #114
    - #115
    - #116

#### Airtable hold a lot of raw data and is fast to update and inspect

- https://airtable.com/applsFPbVXTrmlkLC/tblyGN1GUgxjFhSYa/viw4smxq1PS3jRzqN?blocks=hide

##### We have a placeholder repo with some diagrams

- https://github.com/LL782/dc5b-protocol

##### And a scratch pad in Miro

- https://miro.com/app/board/uXjVO3dkXBo=/?moveToWidget=3458764560836836090&cot=14

### See the source of the idea: 
- https://github.com/LL782/LL782/issues/101#issuecomment-1741758978

**Comment by LL782** [comment]
What should we call such routines? 
- auto-multiplied
- auto-assisted? 

I'm trying to find something to sit alongside "manual" and "automatic". Maybe "multiplied-manul" works?

@anibe I'm making a note of [Buffer](https://buffer.com/) which you mentioned before. Let's try it out and see how it goes (they don't include Wordpress and Tumblr – just sayin')

Lots of platforms (e.g. Wordpress, Tumblr, Instagram) offer to post to other platforms every time you post. [I've also requested a demo with Khoros](https://khoros.com/demo/thank-you-request-demo) and we can research other options. 

I think our budget for now is close to zero (very close) and I love the saying, "don't automated something until you've done it manually". So let's make this ticket about identifying comms routines that would benefit from automatic reposting

**Comment by anibe** [comment]
@LL782 We can probably take advantage of the publishing platforms' in-built promoting tools before signing up for any service. I like "auto-assisted"

**Comment by LL782** [comment]
Sweet -- we're in agreement!

I like "auto-assisted" too. It can cover other things too, like being automatically prompted to post something when a particular business event occurs, like when the latest main image for a given idea is updated that might be a good time to update fans on Instagram. 

Perhaps it won't happen but I'd like to increase the probability that we'll map out the business processes to this level of detail and start to leverage tech to make the less creative tasks happen without us having to spend much time on them.

**Comment by LL782** [comment]
Before I close this one I want to create another issue:
- #113

There probably need to be a few other protocol diagram related issues played before it's ready for adding that information, but you never know, have to start somewhere

- #114
- #115
- #116

**Comment by LL782** [comment]
Issues created
