### ISSUE TITLE
Research if we should use MailChimp or another providers

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#163]
# Why

1. So we can make a decision and start building out the sign-up forms and email templates

# What

- Investigate MailChimp and alternatives
- See if it suits our needs

# Notes

## Requirements of email platform

1. Newsletter sign-up forms
2. Customisable HTML emails

## Nice to haves
3. Transactional email API/solution

## Alternatives to consider

4. Anything in the Google Suite that we could leverage
2. Can we build something into Google Cloud?
3. https://emailoctopus.com looks really good
4. [Previously when I looked at this](https://www.notion.so/dc5b/1-notepad-482a54e39f8d49ddbacdaf61dd33e3aa?pvs=4#e5f199614e07477988a83d82efd03b0b) I was moving towards using [Send Pulse](https://sendpulse.com/)

**Comment by LL782** [comment]
@anibe would you be interested in taking on some research? 😀

**Comment by anibe** [comment]
@LL782 My pleasure 😉

**Comment by anibe** [comment]
@LL782 

[Here’s some initial analysis](https://www.notion.so/dc5b/Marketing-tool-analysis-23a0d4e8cff348a0ad47b9306e1b0776?pvs=4)

**Comment by LL782** [comment]
From this it looks like HubSpot might be the way to go. Where does the
monthly price come from? What are the free tier options for using this for
email newsletter for example?

**Comment by anibe** [comment]
@LL782 you'll find it in the "Starter" [column of this pricing page](https://www.hubspot.com/pricing/suite/starter?products=marketing-hub-starter_1&products=sales-hub-starter_1&products=service-hub-starter_1&products=cms-hub-starter_1&products=operations-hub-starter_1&term=annual) (annual billing selected)

HubSpot does seem to be the enterprise choice, but I was curious about Folk. As you suggested, we should give the free tiers a spin first before committing, but I've found that they limit the feature set so much that you're almost forced to take on a paid plan.

**Comment by LL782** [comment]
Hey @anibe, I've been reviewing again and I like MailChimp. I've always had a good feeling about them (I think because of the chimp), the developer experience is strong, and I like what they (and the new owner Intuit) say on their company story pages. 

Plus the make a strong claim that they are fully featured at a fraction of the cost when you read their comparison page.

Lets give them a try for our initial needs?

For me it's either that or we try out more than one, in my opinion. What do you think?

**Comment by anibe** [comment]
@LL782 Yeah sounds good. Let's run the first trial/campaign with MailChimp and evaluate it after
