### ISSUE TITLE
Design system: Produce designs for fonts, colours and spacing

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#191]
## Why

1. Almost everything we design will need these atoms

## What

- [x] Output decisions on fonts, colours and spacing that we can turn into atomic UI components

## Notes

1. Working in Figma might be faster than working in the browser for this kind of experimentation

## Next step

- #192
- #193

**Comment by LL782** [comment]
Done with this work in Figma

<img width="1194" alt="Screenshot 2023-11-22 at 23 30 34" src="https://github.com/LL782/LL782/assets/353044/d830b2c7-04a9-49fc-8414-fc00a0a4f9a8">

https://www.figma.com/file/jBVbv7sVjOaXlWBD511OMF/DC5B-Design-System

[DC5B Design System.pdf](https://github.com/LL782/LL782/files/13444750/DC5B.Design.System.pdf)

**Comment by LL782** [comment]
@anibe I've drafted colours, fonts and spacing for the design system. Are you able to access and comment on the Figma? 

https://www.figma.com/file/jBVbv7sVjOaXlWBD511OMF?node-id=0:1&locale=en&type=design

Curious to know your thought 💭

**Comment by anibe** [comment]
@LL782 requested access

**Comment by LL782** [comment]
@anibe granted

**Comment by LL782** [comment]
I've started building things into [com.dc5b.com](https://com.dc5b.com)
