### ISSUE TITLE
Goals for 2023-08-10

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#65]
### Fundamentals

- [x] LL782/LL782#75

### Logistics

- [x] LL782/LL782#66
- [x] LL782/LL782#69
- [ ] LL782/LL782#70

### Public Comms

- [ ] LL782/LL782#71
- [ ] LL782/LL782#72

### Product Development

- [ ] LL782/LL782#74

### Technical development

- [ ] **LL782/IDEA.DC5B#88**

## Parked thoughts

1.  Q. What are our strategies for communicating with customers? 
    A. We want... 
      1. the strategies to be well defined 
      2. templates for different communications types to be ready
      3. templates ready for a wide range of platforms
      4. "all based covered" approach where we use lots of platforms to have lots of reach
      5. different platforms have a different purpose
      6. Some notes in Miro [here](https://miro.com/app/board/uXjVO3dkXBo=/?moveToWidget=3458764560836836090&cot=14)
  7. Q. Time for [Buffer](https://buffer.com/)?
      A. No probably not yet. Too pricey
8.  What do we call customers?   
    - Art lovers
    - Customers
    - Clients
    - Connoisseurs
    - Aesthetes
    - Curators
    - Visionaries
    - Appreciators
    - Admirers
    - Collectors
    - Patron
    - Benefactors

**Comment by anibe** [comment]
Love how you've organised the goal tracking here on GitHub! Unlimited "blocks" FTW 😄
