### ISSUE TITLE
Create initial tasks for comms stream

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#71]
# Why

1. To get the comms stream growing
2. [Comms channels are a key part of the organisation](https://miro.com/app/board/uXjVO3dkXBo=/?moveToWidget=3458764560836836090&cot=14)

# What

- [x] Brainstorm ideas for comms
- [x] Turn some into issues in [**Comms stream**](https://github.com/users/LL782/projects/4/views/11) view
- [x] Present to team 
- [x] and make a decision about which to work on first

# Notes

1. Maybe use "priority" to indicate which to work on first
2. Refine them a bit too – naturally
3. This is one of the https://github.com/LL782/LL782/issues/65

**Comment by LL782** [comment]
I've brought this one into play and assigned both of us. The first part is to brainstorm so the more the merrier. At design school they taught us to cast the net wide and then bring it in and refine what we had down from an essay into a couple of words. So don't hold back, throw everything into the mix. 

I'd love to read your ideas, assumptions, hunches and assertions. I'll do the same, adding ideas for tickets as checklist items in descriptions or comments, or go straight to tickets. So long as everything we create is under the comms epic nothing will go to waste.

**Comment by LL782** [comment]
@anibe I've brought this one into play and assigned both of us. The first part is to brainstorm, so the more the merrier! At design school they taught us to cast the net wide and then bring it in and refine what we had. Don't hold back, throw everything into the mix! 

I'd love to read your ideas, assumptions, hunches and assertions. I add idea for tickets as checklist items, in descriptions, comments, and as tickets under the comes epic. You're conversation on any of what I've written would be most welcome and valuable! Thanks 🙏🏼

**Comment by LL782** [comment]
I picture a flow diagram, state machines, a system with queues, triggers and tasks that makes sending comms almost habitual. 

We need to do this and need to do it well so I think a designed system that we can evaluate, reason about and refine is the way to go. 

Don't get me wrong, the content must be heartfelt and real, but the routine is automatic. Feels like one of those examples where defining your own boundaries benefits your creativity within.

**Comment by anibe** [comment]
@LL782 Finally got some time to attend to this. I'm sure you've done a lot more thinking about this so I'm sure nothing I say here should be groundbreaking.

Here's first thing that comes to my mind regarding comms: 

```mermaid
graph LR;
    A[Internal Communications] --> B[P1: Regular team meetings];
    A --> C[P2: Internal messaging platform];
    A --> D[P3: Email updates];

    E[External Communications] --> F[P1: Social media & marketing presence];
    E --> G[P2: Customer newsletters];
    E --> H[P3: Press releases];
```
I've labeled each item in order of importance, with P1 being the highst priority. Basing the ranking on the impact it will have on revenue and productivity.

The other thoughts I have are about process:

- How frequently should we be communicating?
- Tone of voice?
- What platform and tools are we using
- Automated or manual?
- Do you target all the platforms or just the ones we know our audience is ie. Instagram
-  Paid promotion (ads) or organic?

The internal comms I think is more straightforward so I think we should spend more time dissecting the external strategy as that is key for growing clients and friends.

**Comment by LL782** [comment]
Nice one @anibe – I think this is a great start!

Totally agree about external comms being the focus for now. I do have the idea of a street-team and also Patreon members getting comms that aren't public but we can treat like any other platform.

In terms of closing this issue:
- We can keep brainstorming some of the other tickets
- We have some good issues to go forward with
- "Present to the team" feels covered by this async communication
- Make a decision about which to work on next is going to happen naturally.

So I'm going to carry forward some of the notes we've made here to the appropriate other tickets and then close this one. Sound good? 👍

**Comment by anibe** [comment]
@LL782 Excellent! That sounds good

**Comment by LL782** [comment]
# Hey dude, I don't know where to copy that diagram draft to? 

- I thought of another ticket, but that doesn't seem a long term solution. 
- I also thought of a markdown file somewhere in a GitHub repo.
- I'd love to visit a URL and be able to navigate a diagram like a map.

## Where to start?

Obviously I'm planning on the diagram getting a lot more detailed than the one above.
Miro is another option I guess, proven to be good for workshops, but I would like to try Mermaid for a bit. 

### Let's go with a GitHub markdown file!

#### DC5B Protocol

New repo? 

- #95

**Comment by LL782** [comment]
@anibe I've transformed the items from https://github.com/LL782/LL782/issues/71#issuecomment-1736406428 into a checklist on 
- #96

**Comment by anibe** [comment]
@LL782  haven't tried it but I'm sure creating a Gist should also work but the md file is fine too
