### ISSUE TITLE
Draft intentions for each comms channel

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#72]
## Why

1. To inform the comms we put out
2. To avoid supporting any channels that don't have an intended purpose
3. To inform the design of comms templates and assets

### This ties into the plan to have clearly defined protocol around everything, including:

- updating fans on business developments 
- updating fans on art idea development
- updating fans on product development 
- updating fans on exhibition news
- polling fans for reactions to proposals 
- polling fans for new ideas
- thanks fans for poll participation
- inviting fans to make new product requests
- asking fans for specific support
- thanks fans for specific support
- advertising products to boost sales
- advertising the brand to attract people
- advertising events to draw crowds
- publicly communicating campaigns
- publicly announcing events
- responding to general current affairs
- responding to general brand discussion 
- communicating around technical issues
- communicating around political issues
- celebrating technical issue resolution 
- celebrating political issue resolution 
- grieving technical issue defeat 
- grieving political issue defeat
- customer auto comms, transactions, etc. 
- customer manual comms, issues, etc. 
- asking for customer feedback
- asking for customer reviews
- sharing keep in touch options with customers 
- inviting perspective street team member
- welcoming new street team member
- calling on street team to select samples
- calling on street team to review samples
- calling on street team to push campaigns 
- calling on street team to meet-up for fun
- thanking street team for campaign support
- noticing anniversary of team membership
- proposing product collaboration 
- proposing creative collaboration 
- individual general sales chat
- individual general marketing chat

**Comment by LL782** [comment]
@anibe hey dude, can you think of any more for this list? (See notes)

**Comment by anibe** [comment]
@LL782 pretty comprehensive, great work! Can't think of anything else rn. Can we group them?

**Comment by LL782** [comment]
Yep, I think next step is to put them into Airtable and group them. I'll start that now

**Comment by LL782** [comment]
So I've added them to a new table called "Comms routines". I'll link them to **comms channels** and **business events**. We can also add **audience type** (fan, customer, public, organic reach, paid promotion, etc.) and a column related to tone.

@anibe what did you have in mind for groups? Feel free to add something in. 

Do you have editing permission? I've just made you an Owner of the Workspace so you should have:

Airtable > DC5B > [Comms routines](https://airtable.com/applsFPbVXTrmlkLC/tblyGN1GUgxjFhSYa/viw4smxq1PS3jRzqN?blocks=hide)

**Comment by LL782** [comment]
> Can we group them?

Also, if you spot what you think are duplicates, please drop a comment and we can discuss. They might be the same or I might have more info
