### ISSUE TITLE
Brainstorm all "Web Actions"

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#82]
## To reason about which visits and actions across we need to have visibility of

- The brainstorm should encompass all projects. 
- This is about us making data informed decisions
- We have an Airtable for the events here: https://airtable.com/applsFPbVXTrmlkLC/tblbO1PudzE0qYxGw/viwxLiEiQ65ApDkNU

Next step

- [ ] Rank web actions in order of importance to then start work on the most important one ☝️

**Comment by LL782** [comment]
@anibe I've started brainstorming actions on the Airtable. Feel free to join in. It's a brainstorm we can map, filter and reduce later 😁

**Comment by anibe** [comment]
@LL782 Seen your additions, they are pretty comprehensive already. Added some more

**Comment by LL782** [comment]
I've added some more and think we have enough for now. Take a look and if there are any at least as important as those at the top please add them. 

I'm going to close this brainstorm ticket and open another for the next step, which I think is ranking them in order of importance. 

- [ ] Rank web actions in order of importance to then start work on the most important one
