### ISSUE TITLE
List sources for MVP data view

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#88]
## Why

1. To hone in on how we're going to build our first data view

## What

- [x] Add our chosen source for each data point
- [x] Optionally add an idea for a future source

## Notes

1. This will probably be an iteration on [Airtable](https://airtable.com/applsFPbVXTrmlkLC/tblbO1PudzE0qYxGw/viwEFdNcF8aaW4I8L?blocks=hide) 
2. See whatever was done in #87

**Comment by LL782** [comment]
[Airtable > DC5B: Business Events](https://airtable.com/applsFPbVXTrmlkLC/tblbO1PudzE0qYxGw/viwSUSXOeblCnGc9R?blocks=hide) updated

1. Add "Primary funnel" field (checkbox)
2. Add "Primary funnel" view to focus on just those events
3. Add "Data sources" field 
4. Add links to data sources for all "Primary funnel" events

@anibe I'll leave this open for you to review. Please close it if you're happy 👍

**Comment by anibe** [comment]
@LL782 Looks good to me, great work!

Do we need to define the process for updating the data sheet? I'm thinking like a regular weekly or monthly schedule for extracting data from the various sources

**Comment by LL782** [comment]
> Do we need to define the process for updating the data sheet? I'm thinking like a regular weekly or monthly schedule for extracting data from the various sources

It's a worthy question, especially as Vercel only offer the last thirty days. 

Can we try differently though and only pull the data if we are expecting to see something?

e.g. after we've reached out to people or done some campaigning.

Otherwise we'll be pushing ourselves to collect it regardless of need?
