### ISSUE TITLE
Capture usability issues with MVP data viewer

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#89]
## Why

1. It won't be perfect
2. Good to have somewhere to capture ideas for improvement

## What

- [ ] Use this time to review MVP data viewer before the end of this milestone
- [ ] Add ideas for improvement in issues or discussions on the repo
- [ ] Apply the appropriate labels, projects, milestones etc so they are appropriately discoverable 

## Notes

1. This is like a catch all bucket for any defects and enhancement ideas coming out of the rest of the work in this milestone

**Comment by LL782** [comment]
# Issues

## Google sheet with date range

### Comparison between date ranges is very manual and cumbersome 

### Integration with Google data studio, Big Query and Looker is possible

## Data input

### Process from Vercel is entirely manual

### Vercel data includes past 30 days only

**Comment by LL782** [comment]
@anibe I'm finished with this one. I think we can close it and add specific issues as and when they arise. I'll leave it to you to close

**Comment by anibe** [comment]
@LL782 Awesome

**Comment by anibe** [comment]
https://github.com/LL782/LL782/issues/88#issuecomment-1727563180
