### ISSUE TITLE
Draft guidelines for tone of voice for each comms routine

### ISSUE THREAD

**Issue by LL782** [LL782/LL782#98]

**Comment by LL782** [comment]
@anibe I really like this Voice and Tone style-guide from Mailchimp. I'm not saying we should have the same voice – because we shouldn't – but as a reference for how to write a guide. it's great!
- https://styleguide.mailchimp.com/voice-and-tone/

Let's gather other examples?

I love the .GOV design system, it's a very different brand once again but very well designed.
Here's [a "Tone of voice" guide from 2011](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/221398/foi-193-2011-tone-of-voice.pdf) for ref. As I go looking for the root of their style guide I'm finding so many good references:
- https://design-system.service.gov.uk/
- https://www.gov.uk/guidance/government-design-principles
- https://www.gov.uk/government/publications/govuk-content-principles-conventions-and-research-background/govuk-content-principles-conventions-and-research-background
- https://www.gov.uk/guidance/content-design

**Comment by anibe** [comment]
@LL782 Great examples above! The Microsoft style guide is also quite nice
https://learn.microsoft.com/en-us/style-guide/welcome/

**Comment by LL782** [comment]
@anibe how's it going? Where do you think we should draft these guidelines? 

### 🤔 

- Somewhere easy to find
- Somewhere easy to update
- Somewhere good looking

Notion would be good but we hit the limit. 

Perhaps we move Notion things to P2 (https://wordpress.com/p2/)

**Comment by LL782** [comment]
@anibe so we can try it, I've invited you to https://dc5bp2general.wordpress.com/ with your DC5B address

_Aside: if you're up for it I think we can bring the Notion content over_

**Comment by anibe** [comment]
@LL782 Got the invite. I'll have a play

**Comment by LL782** [comment]
# First draft released

Added a first draft to cover each tone here:
- https://com.dc5b.com/guidelines/tone-and-voice

The three tones covered in this guideline are assigned to each routine in Airtable
- https://airtable.com/applsFPbVXTrmlkLC/tblyGN1GUgxjFhSYa/viwaLAnks2wQ8Ux4t?blocks=hide
